version: '2'
services:
  data:
    build: ./data
    volumes:
      - ../:/data
      - /var/lib/mysql
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: character_sheet
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
    volumes_from:
      - data
  php:
    build: ./php
    ports:
#      - '(any port No. you want is OK):80'
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql
  composer:
    build: ./composer
    volumes_from:
      - data
  npm:
    build: ./npm
    volumes_from:
      - data
  php-artisan:
    build: ./php-artisan
    volumes_from:
      - data
    depends_on:
      - mysql
