swagger: "2.0"
info:
  description: "Charashee's API Doc"
  version: "0.0.1"
  title: "Charashee"
host: localhost:10010
basePath: "/api"
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
  - http
  - https
paths:
  "/user":
    get:
      summary: "ユーザ情報取得"
      description: "APIをコールしたユーザーの情報を返す"
      responses:
        200:
          description: "成功"
          schema:
            type: object
            properties:
              id:
                type: "integer"
                example: 1
              name:
                type: "string"
                example: "test_user"
              email:
                type: "string"
                example: "test@example.com"
  "/user/characters":
    get:
      summary: "ユーザーに紐づくキャラクター一覧"
      description: "ユーザーに紐づくキャラクターの情報リストを返す"
      responses:
        200:
          description: "成功"
          schema:
            type: object
            properties:
              characters:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "テスト"
                    age:
                      type: integer
                      example: 24
                    sex:
                      type: string
                      example: "男"
                    job:
                      type: string
                      example: "ニート"
                    str:
                      type: integer
                      example: 10
                    con:
                      type: integer
                      example: 10
                    dex:
                      type: integer
                      example: 10
                    pow:
                      type: integer
                      example: 10
                    app:
                      type: integer
                      example: 10
                    siz:
                      type: integer
                      example: 10
                    int:
                      type: integer
                      example: 10
                    edu:
                      type: integer
                      example: 10
                    comment:
                      type: string
                      example: "テストキャラクター"
              id:
                type: integer
                example: 1
              name:
                type: string
                example: "テスト"
